name: test_dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  buffer: any
  hex: any
  dartros: any
  std_msgs: ^0.0.3

dependency_overrides:
  dartros:
    path: ../dartros
  std_msgs:
    path: ../std_msgs

dev_dependencies:
  build_runner: any
