// Auto-generated. Do not edit!

// Updated: Thu Dec 17 15:41:12 2020

// (in-package test_dart.msg)


import 'dart:convert';
import 'package:buffer/buffer.dart';
import 'package:dartros/msg_utils.dart';

//-----------------------------------------------------------

class CoffeeResult extends RosMessage<CoffeeResult> {
  double mass;

  RosTime duration;

  static CoffeeResult $prototype = CoffeeResult();
  CoffeeResult({ 
    double mass,
    RosTime duration,
  }):
  this.mass = mass ?? 0.0,
  this.duration = duration ?? RosTime(secs: 0, nsecs: 0);

  CoffeeResult call({ 
    double mass,
    RosTime duration,
  }) => CoffeeResult(
  mass: mass,
  duration: duration,
  );

  void serialize(ByteDataWriter writer) {
    // Serializes a message object of type CoffeeResult
    // Serialize message field [mass]
    writer.writeFloat32(mass);
    // Serialize message field [duration]
    writer.writeTime(duration);
  }

  @override
  CoffeeResult deserialize(ByteDataReader reader) {
    //deserializes a message object of type CoffeeResult
    final data = CoffeeResult();
    // Deserialize message field [mass]
    data.mass = reader.readFloat32();
    // Deserialize message field [duration]
    data.duration = reader.readTime();
    return data;
  }

  int getMessageSize() {
    return 12;
  }

  @override
  String get fullType {
    // Returns string type for a message object
    return 'test_dart/CoffeeResult';
  }

  @override
  String get md5sum {
    //Returns md5sum for a message object
    return 'ae528ebf7044398995f3387836cbad76';
  }

  @override
  String get messageDefinition {
    // Returns full string definition for message
    return '''# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#result definition
float32 mass
duration duration

''';
  }

}

