// Auto-generated. Do not edit!

// Updated: Mon Feb  1 12:03:04 2021

// (in-package test_dart.msg)


// ignore_for_file: unused_import, overridden_fields
import 'dart:convert';
import 'package:buffer/buffer.dart';
import 'package:dartros_msgutils/msg_utils.dart';
import 'package:actionlib_msgs/msgs.dart';
import 'package:std_msgs/msgs.dart';
import 'CoffeeGoal.dart';

//-----------------------------------------------------------

class CoffeeActionGoal extends RosActionGoal<CoffeeGoal, CoffeeActionGoal> {
  @override
  Header header;

  @override
  GoalID goal_id;

  @override
  CoffeeGoal goal;

  static CoffeeActionGoal $prototype = CoffeeActionGoal();
  CoffeeActionGoal({ 
    Header? header,
    GoalID? goal_id,
    CoffeeGoal? goal,
  }):
  this.header = header ?? Header(),
  this.goal_id = goal_id ?? GoalID(),
  this.goal = goal ?? CoffeeGoal();

  @override
  CoffeeActionGoal call({ 
    Header? header,
    GoalID? goal_id,
    CoffeeGoal? goal,
  }) => CoffeeActionGoal(
  header: header,
  goal_id: goal_id,
  goal: goal,
  );

  void serialize(ByteDataWriter writer) {
    // Serializes a message object of type CoffeeActionGoal
    // Serialize message field [header]
    header.serialize(writer);
    // Serialize message field [goal_id]
    goal_id.serialize(writer);
    // Serialize message field [goal]
    goal.serialize(writer);
  }

  @override
  CoffeeActionGoal deserialize(ByteDataReader reader) {
    //deserializes a message object of type CoffeeActionGoal
    final data = CoffeeActionGoal();
    // Deserialize message field [header]
    data.header = Header.$prototype.deserialize(reader);
    // Deserialize message field [goal_id]
    data.goal_id = GoalID.$prototype.deserialize(reader);
    // Deserialize message field [goal]
    data.goal = CoffeeGoal.$prototype.deserialize(reader);
    return data;
  }

  int getMessageSize() {
    var length = 0;
    length += header.getMessageSize();
    length += goal_id.getMessageSize();
    length += goal.getMessageSize();
    return length;
  }

  @override
  String get fullType {
    // Returns string type for a message object
    return 'test_dart/CoffeeActionGoal';
  }

  @override
  String get md5sum {
    //Returns md5sum for a message object
    return '72e99e8dd11e6d676a3ab86a19792150';
  }

  @override
  String get messageDefinition {
    // Returns full string definition for message
    return '''# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
CoffeeGoal goal

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: test_dart/CoffeeGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
CoffeeSpec spec

================================================================================
MSG: test_dart/CoffeeSpec
string name
float32 grind_size
float32 mass

''';
  }

}

