// Auto-generated. Do not edit!

// Updated: Mon Feb  1 12:03:04 2021

// (in-package test_dart.msg)


// ignore_for_file: unused_import, overridden_fields
import 'dart:convert';
import 'package:buffer/buffer.dart';
import 'package:dartros_msgutils/msg_utils.dart';
import 'CoffeeSpec.dart';

//-----------------------------------------------------------

class CoffeeGoal extends RosMessage<CoffeeGoal> {
  CoffeeSpec spec;

  static CoffeeGoal $prototype = CoffeeGoal();
  CoffeeGoal({ 
    CoffeeSpec? spec,
  }):
  this.spec = spec ?? CoffeeSpec();

  @override
  CoffeeGoal call({ 
    CoffeeSpec? spec,
  }) => CoffeeGoal(
  spec: spec,
  );

  void serialize(ByteDataWriter writer) {
    // Serializes a message object of type CoffeeGoal
    // Serialize message field [spec]
    spec.serialize(writer);
  }

  @override
  CoffeeGoal deserialize(ByteDataReader reader) {
    //deserializes a message object of type CoffeeGoal
    final data = CoffeeGoal();
    // Deserialize message field [spec]
    data.spec = CoffeeSpec.$prototype.deserialize(reader);
    return data;
  }

  int getMessageSize() {
    var length = 0;
    length += spec.getMessageSize();
    return length;
  }

  @override
  String get fullType {
    // Returns string type for a message object
    return 'test_dart/CoffeeGoal';
  }

  @override
  String get md5sum {
    //Returns md5sum for a message object
    return '0d2296f98f84fa609fddf8e6bf1807ff';
  }

  @override
  String get messageDefinition {
    // Returns full string definition for message
    return '''# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
CoffeeSpec spec

================================================================================
MSG: test_dart/CoffeeSpec
string name
float32 grind_size
float32 mass

''';
  }

}

