// Auto-generated. Do not edit!

// Updated: Mon Feb  1 12:03:04 2021

// (in-package test_dart.msg)


// ignore_for_file: unused_import, overridden_fields
import 'dart:convert';
import 'package:buffer/buffer.dart';
import 'package:dartros_msgutils/msg_utils.dart';

//-----------------------------------------------------------

class CoffeeFeedback extends RosMessage<CoffeeFeedback> {
  double mass;

  static CoffeeFeedback $prototype = CoffeeFeedback();
  CoffeeFeedback({ 
    double? mass,
  }):
  this.mass = mass ?? 0.0;

  @override
  CoffeeFeedback call({ 
    double? mass,
  }) => CoffeeFeedback(
  mass: mass,
  );

  void serialize(ByteDataWriter writer) {
    // Serializes a message object of type CoffeeFeedback
    // Serialize message field [mass]
    writer.writeFloat32(mass);
  }

  @override
  CoffeeFeedback deserialize(ByteDataReader reader) {
    //deserializes a message object of type CoffeeFeedback
    final data = CoffeeFeedback();
    // Deserialize message field [mass]
    data.mass = reader.readFloat32();
    return data;
  }

  int getMessageSize() {
    return 4;
  }

  @override
  String get fullType {
    // Returns string type for a message object
    return 'test_dart/CoffeeFeedback';
  }

  @override
  String get md5sum {
    //Returns md5sum for a message object
    return 'bc896cc245a01cb882740a335971513f';
  }

  @override
  String get messageDefinition {
    // Returns full string definition for message
    return '''# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#feedback
float32 mass


''';
  }

}

